# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- deploy

sast:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
include:
- template: Security/SAST.gitlab-ci.yml

deploy-prod:
  stage: deploy
  image: registry.gitlab.com/andrielson/odin-rio-preto-nestjs:gitlab-ci
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - cd /srv
    - node dist/main