image: node:lts-alpine3.14

stages:
  - test
  - build
  - deploy

# Cache modules in between jobs
cache: &global_cache
  key:
    files:
      - yarn.lock
  paths:
    - .yarn-cache/
    - node_modules/

install-dependencies:
  stage: .pre
  script:
    - yarn install --cache-folder .yarn-cache --frozen-lockfile --prefer-offline

unit-tests:
  stage: test
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  script:
    - echo "Executing unit tests..."

build-artifacts:
  stage: build
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  script:
    - yarn build
    - yarn install --cache-folder .yarn-cache --ignore-scripts --prefer-offline --production
  artifacts:
    paths:
      - dist/
      - node_modules/
      - package.json

push-image:
  stage: deploy
  cache: []
  before_script: []
  script:
    - echo "Building Docker image..."
