image: node:lts-alpine3.14

stages:
  - test
  - build
  - deploy

# Cache modules in between jobs
cache: &global_cache
  - key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
      - node_modules/

install-dependencies:
  stage: .pre
  script:
    - echo $(pwd)
    - ls -lha
    - yarn install --cache-folder .yarn-cache --frozen-lockfile --prefer-offline
    - du -sh node_modules/

unit-tests:
  stage: test
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  script:
    - echo $(pwd)
    - ls -lha
    - echo "Executing unit tests..."
    - du -sh node_modules/

build-artifacts:
  stage: build
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  script:
    - echo $(pwd)
    - ls -lha
    - yarn build
    - yarn install --cache-folder .yarn-cache --ignore-scripts --prefer-offline --production
    - du -sh node_modules/
    - touch ./node_modules/___andrielson
  artifacts:
    paths:
      - dist/
      - node_modules/
      - package.json

push-image:
  stage: deploy
  cache: []
  before_script: []
  script:
    - echo $(pwd)
    - ls -lha
    - du -sh node_modules/
    - echo "Building Docker image..."
    - ls -lha ./node_modules/ | head
