image: node:lts-alpine3.14

stages:
  - test
  - build
  - deploy

# Cache modules in between jobs
cache:
  - key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/

install-dependencies:
  stage: .pre
  script:
    - yarn install --cache-folder .yarn-cache --frozen-lockfile --prefer-offline

unit-tests:
  stage: test
  cache:
    key:
      files:
        - yarn.lock
    policy: pull
  script:
    - echo "Executing unit tests..."

build-artifacts:
  stage: build
  cache:
    key:
      files:
        - yarn.lock
    policy: pull
  script:
    - yarn build
    - yarn install --production --ignore-scripts --prefer-offline
  artifacts:
    paths:
      - dist/
      - node_modules/
      - package.json
# deploy-prod:
#   stage: execute
#   image: registry.gitlab.com/andrielson/odin-rio-preto-nestjs:gitlab-ci
#   cache: []
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule"
#   before_script: []
#   script:
#     - cd /srv
#     - node dist/main
